// Variables used by Scriptable.
// These must be at the very top of the file. Do not edit.
// icon-color: green; icon-glyph: book;
/*
VERSION = "1.1.2"
This is a guide for what to do after installing my scripts:
1. Run init.js, follow any instructions given
2. Go into settings in Scriptable
3. Scroll down to "Bookmarks"
4. Add the following ([Bookmark Name] - [Script Filename]):
    absorbLib - absorbLib.js
    adaptationLib - adaptationLib.js
    avenLib - avenLib.js
    eddaLib - eddaLib.js
    lucaLib - lucaLib.js
    FBM - flagBackgroundModule.js
    clipboards - any clipboard folder in the scriptable iCloud folder (folder, BUT NOT BOOKMARK is generated by init.js)
Good job!
This will be updated for other libraries when I feel like it.
*/